kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: {{ .Release.Name }}-composition-overview-panel
  namespace: {{ .Release.Namespace }}
spec:
  widgetData:
    actions: {}
    items:
      - resourceRefId: composition-overview-panel-paragraph
  resourcesRefs:
    items:
    - id: composition-overview-panel-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: {{ .Release.Name }}-composition-overview-panel-paragraph
      namespace: {{ .Release.Namespace }}
      resource: paragraphs
      verb: GET